name: Main

on:
  workflow_dispatch

jobs:
  main:
    name: main
    runs-on: ubuntu-latest
    steps:
    - name: Setup Snyk
      uses: snyk/actions/setup@master
    - run: |
        which snyk
        snyk --help
